### PR TITLE
Fix the name of the fixer.

### PR DESCRIPTION
**Pull request by sallner**
otherwise an error is raised.

### CODE REVIEW

**Comment by hroncok** [comment]
@encukou Our test is broken :(

**Comment by sallner** [comment]
@hroncok sorry for bringing that up :sweat: 

Looks like modernize changed the way to import it and that the import here was not necessary at all as it is only called in the subprocess. I improved the regex for fixer detection to include more typos.

**Comment by hroncok** [comment]
> @hroncok sorry for bringing that up

Don't be sorry, that's great actually!

**Review by hroncok — COMMENTED** [review]
I like the change and I'm 90% sure the `modernize` import was a left over, not something clever on purpose. For the remaining 10%, I ask @encukou for review.

**Review by encukou — APPROVED** [review]

**Comment by encukou** [comment]
More than 10% from me :)
Thank you!

**Pull request merged**
