### PR TITLE
Remove a confusing underscore

### PR DESCRIPTION
**Pull request by hroncok**
I have no idea why it is there, yet I had to think about it.

If there is an actual reason please tell me and close this.

### CODE REVIEW

**Comment by hroncok** [comment]
tests failure unrelated, fixed in https://github.com/fedora-python/portingguide/pull/42

**Comment by frenzymadness** [comment]
The first code example doesn't work in all stable Pythons so I think that it's just a typo. Or did you find any explanation?

**Comment by hroncok** [comment]
I haven't. But this can wait for @encukou.

**Comment by encukou** [comment]
Yes, just a typo. Thanks for noticing!

**Pull request merged**
